blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

# admin.site.site_title = "Blog_site"
admin.site.site_header = 'Django-Blog'

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('register/', user_views.register, name='register'),
                  path('profile/', user_views.profile, name='profile'),
                  path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
                  path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
                  path('password-reset/',
                       auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
                       name='password_reset'),
                  path('password-reset/done/',
                       auth_views.PasswordResetDoneView.as_view(template_name='users/done_pass_reset.html'),
                       name='password_reset_done'),
                  path('password-reset-confirm/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(template_name='users/confirm_pass_reset.html'),
                       name='password_reset_confirm'),
                  path('password-reset-complete/',
                       auth_views.PasswordResetCompleteView.as_view(template_name='users/complete_pass_reset.html'),
                       name='password_reset_complete'),
                  path('', include('blog_app.urls')),
                  path('blog_api/', include('blog_apis.urls')),
                  path('__debug__/', include('debug_toolbar.urls')),

              ]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path
from .views import home, data, CreateBlog, BlogListView, DeleteBlog, UserBlogListView, BlogDetailView, UpdateBlog

urlpatterns = [
    path('', home, name='home'),
    path('data', data, name='data'),
    path('create', CreateBlog.as_view(), name='create'),
    path('my_blog', BlogListView.as_view(), name='my_blog'),
    path('my_blog/<int:pk>', BlogDetailView.as_view(), name='blog-detail'),
    path('my_blog/<int:pk>/update', UpdateBlog.as_view(), name='blog-update'),
    path('<str:email>/user', UserBlogListView.as_view(), name='user_blog_list'),
    path('my_blog/<int:pk>/delete', DeleteBlog.as_view(), name='delete_blog'),

]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
# from django.urls import reverse
import uuid




# class BaseModel(models.Model):
#     uid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
#     created_at =models.DateField(auto_now_add=True)
#     updated_at=models.DateField(auto_now_add=True) #check here while using auto_now=True
#
#     class Meta:
#         abstract=True
#
#
# class BlogCategory(BaseModel):
#     category_name=models.CharField(max_length=100)

class Blog(models.Model):
# class Blog(BaseModel):
#     category=models.ForeignKey(BlogCategory, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=255, unique=True, default="")
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    content = models.CharField(max_length=255, default="")
    blog_image = models.ImageField(upload_to='documents/', default="")
    is_deleted = models.BooleanField(default=False)

    # created_at = models.DateField(auto_now=True, blank=True, null=True)

    # def get_absolute_url(self):
    #     return reverse('home')

    # def __str__(self):
    #     return self.title

blog_app/forms.py
from .models import Blog
from django.forms import ModelForm


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'

blog_app/views.py
from django.shortcuts import render
from .models import Blog
from django.views.generic import ListView, DeleteView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model


def home(request):
    context = {
        'blogs' : Blog.objects.all()
    }
    return render(request, "blog_app/home.html", context)


def data(request):
    if request.method == "Post":
        title = request.POST.get('title')
        created_by = request.POST.get('created_by')
        content = request.POST.get('content')
        model_var = Blog(title=title, created_by=created_by, content=content)
        model_var.save()

    return render(request, "data.html")


class BlogListView(ListView):
    model = Blog
    template_name = 'blog_app/home.html'
    context_object_name = 'blogs'


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog_app/blog_detail.html'


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = "blog_app/create.html"
    fields = ['title', 'content', 'blog_image']
    success_url = reverse_lazy('home')
    success_message = 'New blog added successfully'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class UserBlogListView(ListView):
    model = Blog
    template_name = 'blog_app/user_blog.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        # breakpoint()
        context = super(UserBlogListView, self).get_context_data(**kwargs)
        user = get_object_or_404(get_user_model(), email=self.kwargs.get('email'))
        blogs = Blog.objects.filter(created_by=user)
        context['blogs'] = blogs
        context['user'] = user
        # breakpoint()
        return context


class UpdateBlog(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Blog
    template_name = "blog_app/create.html"
    fields = ['title', 'content', 'blog_image']
    success_url = '/'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        blog =self.get_object()
        if self.request.user == blog.created_by:
            return True
        return False


class DeleteBlog(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    success_url = '/'
    template_name = "blog_app/confirm_delete.html"
    queryset = Blog.objects.all()

    def test_func(self):
        blog =self.get_object()
        if self.request.user == blog.created_by:
            return True
        return False

blog_app/templates/blog_app/base.html
{% load static %}
<!DOCTYPE html>
<html xml:lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    {% if title %}
        <title>Blogpost - {{ title }}</title>
    {% else %}
        <title>Blogpost App</title>
    {% endif %}
</head>
<body>
            <br><br><br>
            <div class="col-md-8">
              {% if user.is_authenticated %}
              <h3>Hello {{ user }}</h3>
              {% endif %}
            </div>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-danger fixed-top">
        <div class="container">
          <a class="navbar-brand mr-5" href="/">Blogpost</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="#">About</a>
            </div>

            <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'create' %}">New Post</a>
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                  <a class="nav-item nav-link" href="{% url 'my_blog' %}">All Blog/s</a>
                  <a class="nav-item nav-link" href="{% url 'user_blog_list' user.email %}">My Blog/s</a>


                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
              {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
              {% endif %}
                <br>
              {% block content %}{% endblock %}
            </div>
            <br><br><br>

        </div>

    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog_app/templates/blog_app/blog_detail.html
{% extends "blog_app/base.html" %}
<body>
{% block content %}
<br><br><br>
      <li>{{ object.title }}</li>
            <ul>
               <li>{{ object.id }}</li>
                  <li>{{ object.content }}</li>
                  <li>{{ object.blog_image }}</li>
           </ul>
        {% if object.created_by == user %}
            <a href="{% url 'blog-update' blog.id %}">Update</a>
            <a href="{% url 'delete_blog' blog.id %}">Delete</a>
        {% endif %}
        <br><br><br>
{% endblock %}
</body>

blog_app/templates/blog_app/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% extends 'blog_app/base.html' %}
<body>
    {% block content %}
    <br><br><br>
    <form method="post">
        {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
    {% endblock %}
</body>
</html>

blog_app/templates/blog_app/create.html
{% extends 'blog_app/base.html' %}
{% block content %}

<section class="section">
    <div class="container">
        <br><br><br>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="fw-bold">Create your blog</h2>
                    </div>
                    <div class="card-body">
                        <form method = "POST" enctype="multipart/form-data">
                            {% csrf_token %}
<!--                            {{ form.as_p }}-->
                             <div class="mb-3">
                                <label class = "form-label">Title : </label>
<!--                                <input type="text" id="title" name="title"><br><br>-->
                                 {{ form.title }}
                             </div>

                             <div class="mb-3">
<!--                                <label for="content">content :</label>-->
<!--                                <input type="text" id="content" name="content"><br><br>-->
                                 <label class = "form-label">Content : </label>
                                 {{ form.content }}
                             </div>
                             <div class="mb-3">
<!--                                <label>Your Image File-->
<!--                                  <input type="file" name="myImage" />-->
                                 <label class = "form-label">Image : </label>
                                    {{ form.blog_image }}
<!--                                </label>-->
                             </div>
                            <br><br>
                            <button type="submit" value="Submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog_app/templates/blog_app/data.html
<html>
<body>
<h2> Data saved </h2>
</body>
</html>

blog_app/templates/blog_app/home.html
{% extends "blog_app/base.html" %}
<body>
{% block content %}
    {% for blog in blogs %}
        <li><a href="{% url 'blog-detail' blog.id %}">{{ blog.title }}</a></li>
             <ul>
                 <li>{{ blog.id }}</li>
                    <li>{{ blog.content }}</li>
                    <li>{{ blog.blog_image }}</li>
             </ul>
    {% endfor %}
{% endblock %}
</body>

blog_app/templates/blog_app/my_blog.html
{% extends 'blog_app/base.html' %}
<body>
    {% block content %}
        <h1> These are my blogs:</h1><br>
      {% for blog in blog_list %}
            <li>{{ blog.title }}</li>
             <ul>
                 <li>{{ blog.id }}</li>
<!--                     <li>{{ blog.created_by }}</li>-->
                    <li>{{ blog.content }}</li>
                    <li>{{ blog.blog_image }}</li>
             </ul>
            <form method="POST">
                {% csrf_token %}
                <button type="button">
                    <a href="{% url 'delete_blog' blog.id %}">Delete</a>
                </button>
            </form>
            <br><br>
        {% endfor %}
    {% endblock %}
</body>

blog_app/templates/blog_app/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>

blog_app/templates/blog_app/user_blog.html
<!--{% extends 'blog_app/base.html' %}-->

<body>
{% block content %}
        <h1> These are my blogs:</h1><br>

      {% for blog in blogs %}
            <li>{{ blog.title }}</li>
             <ul>
                 <li>{{ blog.id }}</li>
                    <li>{{ blog.content }}</li>
                    <li>{{ blog.blog_image }}</li>
             </ul>
        {% if object.created_by == user %}
            <a href="{% url 'blog-update' blog.id %}">Update</a>
            <a href="{% url 'delete_blog' blog.id %}">Delete</a>
        {% endif %}
     {% endfor %}
{% endblock content %}
</body>